version: '3.3'


services:
  server:
    depends_on:
      - mysql
    links:
      - mysql
    build: ./src
    ports:
      - "5000:5000"
    networks:
      - network-api

  mysql:
    image: mysql:5.7
    ports:
      - "32000:3306"
    volumes:
      - ./db/meteorology-db:/var/lib/mysql
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - network-api
      - networks-gui
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Meteorologie
      MYSQL_USER: meteo-admin
      MYSQL_PASSWORD: meteo

  mysql-workbench:
    depends_on:
      - mysql
    image: ghcr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      - TZ=Europe/Bucharest
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    networks:
      - networks-gui


networks:
  network-api: {}
  networks-gui: {}


volumes:
  meteorology-db: {}
