version: '3.3'


services:
  server:
    depends_on:
      - mysql
    links:
      - mysql
    build: ./src
    ports:
      - "5000:5000"
    restart: always
    networks:
      - network-api

  mysql:
    image: mysql:5.7
    ports:
      - "32000:3306"
    volumes:
      - ./db/meteorology-db:/var/lib/mysql
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - network-api
    environment:
      MYSQL_ROOT_PASSWORD: root


networks:
  network-api: {}


volumes:
  meteorology-db: {}
