version: '3.7'


services:
  broker:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - '1883'
    ports:
      - '1883:1883'
    networks:
      - network-broker

  server:
    depends_on:
      - broker
    links:
      - broker
    build: ./src
    image: server
    container_name: server
    networks:
      - network-broker
      - network-db

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./db/influxdb-storage:/var/lib/influxdb
    networks:
      - network-db
      - network-gui

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    container_name: grafana
    ports:
      - '80:3000'
    # volumes:
      # - ./grafana-provisioning/:/etc/grafana/provisioning
      # - ./db/grafana-storage:/var/lib/grafana
    env_file: envs/grafana.env
    networks:
      - network-gui


networks:
  network-broker:
    name: network-broker
  network-db:
    name: network-db
  network-gui:
    name: network-gui


volumes:
  influxdb-storage:
    name: influxdb-storage
